alias: AC-Laden deaktivieren bei maximalem SOC oder zu wenig Solarleistung
trigger:
  - platform: numeric_state
    entity_id: sensor.battery_0001_state_of_charge_soc
    above: input_number.soc_max_pylontech
  - platform: numeric_state
    entity_id: input_number.solar_threshold
    below: 750
    for:
      minutes: 2
condition:
  - condition: state
    entity_id: switch.ac_laden
    state: "on"
action:
  - service: switch.turn_off
    target:
      entity_id: switch.ac_laden
